import React, { useState } from 'react'
import Head from 'next/head'
import Layout from '../components/Layout'
import SearchBar from '../components/SearchBar/SearchBar'
import Coins from '../components/Coins/Coins'


export default function Home({ data }) {
  const [search, setSearch] = useState('');

  const filteredAllCoins = data.filter(coin =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleChange = (e) => {
    setSearch(e.target.value.toLowerCase())
  }

  return (
    <Layout>
      <div>
        <Head>
          <title>Next | Crypto Currency</title>
          <meta name="description" content="Generated by Esrafil Elahi" />
        </Head>

        <SearchBar value={search} type='text' placeholder='search' onChange={handleChange} />
        <Coins data={filteredAllCoins} />

      </div>

    </Layout>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch("https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=20&page=1&sparkline=false&price_change_percentage=24h")
  const data = await res.json()

  return {
    props: { data }
  }
}
